$(document).ready(function() {
  var _that = this;
  // Block#: UT?iJXijxyeD^1sjg+Va
  function on_Button_click(e) {
    try {
      // Block#: C]-N,$e8BDg+.${~k/0X
      com.fc.JavaScriptDistLib.Screen.setProperty["Background color"]("ciao", '#ff0000'); // Block#: +6mytfVHH7UqtwW`#?22
      com.fc.JavaScriptDistLib.Container.setProperty["Background color"]("Container", '#ffcc00');
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  $('[obj-name="ciao"]').show();
});
// Generated by snapp
// 963474-819486-928362-463455
